version: '3'

services:
  web:
    container_name: ${APP_NAME}_web
    build:
      context: ./docker/web
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/app
  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7.26
    command: --sort_buffer_size=16M
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=crm
  cache:
    container_name: ${APP_NAME}_cache
    image: redis:5.0.5
    ports:
      - 6379:6379
